import os
import requests

def code_refactoring(path: str) -> str:
    """Uses Llama 3.1 via Ollama to refactor code files for better readability, performance, and architecture."""
    clean_path = path.strip("'\"")
    
    if not os.path.exists(clean_path):
        return f"[code_refactoring] Error: File '{clean_path}' does not exist."
        
    try:
        with open(clean_path, "r", encoding="utf-8") as f:
            code_content = f.read()
            
        file_extension = os.path.splitext(clean_path)[1]
        
        prompt = (
            f"Act as an expert software architect. Refactor the following code file '{clean_path}' "
            f"to improve its maintainability, readability, performance, and adherence to clean coding standards "
            f"(e.g., PEP 8 for Python, SOLID principles). Keep the code functionality identical. "
            f"Provide the complete refactored version of the code inside a code block, followed by a brief summary of your structural changes.\n\n"
            f"Original Code:\n```{file_extension}\n{code_content}\n```"
        )
        
        url = "http://localhost:11434/api/generate"
        payload = {
            "model": "llama3.1",
            "prompt": prompt,
            "stream": False
        }
        
        response = requests.post(url, json=payload, timeout=60)
        
        if response.status_code == 200:
            result_json = response.json()
            refactored_report = result_json.get("response", "No refactoring response generated by the model.")
            return f"[code_refactoring] Optimization Complete for {clean_path}:\n\n{refactored_report}"
        else:
            return f"[code_refactoring] Ollama connection succeeded but returned status code: {response.status_code}"
            
    except requests.exceptions.ConnectionError:
        return "[code_refactoring] Error: Connection refused by local Ollama service. Run 'ollama serve' first."
    except Exception as e:
        return f"[code_refactoring] Internal handler failure. Error: {str(e)}"


SKILLS = [
    {
        "name": "code_refactoring",
        "description": "Refactors a file using Llama 3.1 to clean up structure, optimize performance, and improve clean code metrics.",
        "trigger_phrases": ["refactor", "clean up code", "optimize code", "restructure code", "improve code quality"],
        "func": code_refactoring,
    },
]