import os
import requests

def debugging(path: str) -> str:
    """Uses Llama 3.1 via Ollama to identify bugs, analyze logical errors, and provide actionable fixes for a code file."""
    clean_path = path.strip("'\"")
    
    if not os.path.exists(clean_path):
        return f"[debugging] Error: File '{clean_path}' does not exist."
        
    try:
        with open(clean_path, "r", encoding="utf-8") as f:
            code_content = f.read()
            
        file_extension = os.path.splitext(clean_path)[1]
        
        prompt = (
            f"Act as an expert systems debugger. Inspect the following script '{clean_path}' for compilation errors, "
            f"runtime issues, race conditions, edge-case crashes, or anti-patterns. "
            f"Clearly call out the problems found and provide explicit corrected code snippets to fix them.\n\n"
            f"Target Code:\n```{file_extension}\n{code_content}\n```"
        )
        
        url = "http://localhost:11434/api/generate"
        payload = {
            "model": "llama3.1",
            "prompt": prompt,
            "stream": False
        }
        
        response = requests.post(url, json=payload, timeout=60)
        
        if response.status_code == 200:
            result_json = response.json()
            debug_report = result_json.get("response", "No debugging response generated by the model.")
            return f"[debugging] Diagnostics Report for {clean_path}:\n\n{debug_report}"
        else:
            return f"[debugging] Ollama connection succeeded but returned status code: {response.status_code}"
            
    except requests.exceptions.ConnectionError:
        return "[debugging] Error: Connection refused by local Ollama service. Run 'ollama serve' first."
    except Exception as e:
        return f"[debugging] Internal handler failure. Error: {str(e)}"


SKILLS = [
    {
        "name": "debugging",
        "description": "Scans a file using Llama 3.1 to pinpoint software bugs, logical exceptions, and generate structural solutions.",
        "trigger_phrases": ["debug", "find bugs", "fix error", "troubleshoot script", "diagnose code"],
        "func": debugging,
    },
]