import os
import requests

def unit_testing(path: str) -> str:
    """Uses Llama 3.1 via Ollama to automatically generate comprehensive unit tests for a target source file."""
    clean_path = path.strip("'\"")
    
    if not os.path.exists(clean_path):
        return f"[unit_testing] Error: File '{clean_path}' does not exist."
        
    try:
        with open(clean_path, "r", encoding="utf-8") as f:
            code_content = f.read()
            
        file_extension = os.path.splitext(clean_path)[1]
        
        prompt = (
            f"Act as a professional QA and test automation engineer. Generate a complete, production-ready "
            f"unit test suite for the following source file '{clean_path}'. "
            f"Cover positive cases, negative cases, boundary/edge conditions, and exception handling. "
            f"Provide the complete test code inside a single code block ready to be saved.\n\n"
            f"Target Source Code:\n```{file_extension}\n{code_content}\n```"
        )
        
        url = "http://localhost:11434/api/generate"
        payload = {
            "model": "llama3.1",
            "prompt": prompt,
            "stream": False
        }
        
        response = requests.post(url, json=payload, timeout=60)
        
        if response.status_code == 200:
            result_json = response.json()
            test_suite = result_json.get("response", "No test suite response generated by the model.")
            return f"[unit_testing] Test Suite Generation Complete for {clean_path}:\n\n{test_suite}"
        else:
            return f"[unit_testing] Ollama connection succeeded but returned status code: {response.status_code}"
            
    except requests.exceptions.ConnectionError:
        return "[unit_testing] Error: Connection refused by local Ollama service. Run 'ollama serve' first."
    except Exception as e:
        return f"[unit_testing] Internal handler failure. Error: {str(e)}"


SKILLS = [
    {
        "name": "unit_testing",
        "description": "Analyzes a file using Llama 3.1 and generates a robust, edge-case safe automated unit test suite.",
        "trigger_phrases": ["unit test", "write tests", "generate unit tests", "create a test suite", "test my file"],
        "func": unit_testing,
    },
]